language: julia

os:
  - linux

julia:
  - 1.2

notifications:
    email: false

jobs:
  include:
    - stage: "Tests"
#    - stage: "Documentation"
#      julia: 1.2
#      os: linux
#      script:
#        - export DOCUMENTER_DEBUG="true"
#        - julia --color=yes --project=docs/ -e 'using Pkg;
#                                                Pkg.add("Documenter");
#                                                Pkg.add(PackageSpec(url="https://github.com/ww1g11/JuMag.jl"));
#                                                Pkg.instantiate();
#                                                Pkg.develop(PackageSpec(path=pwd()));
#                                                Pkg.build()'
#        - julia --color=yes --project=docs/ docs/make.jl
#      after_success: skip
